trigger:
- main

pool:
  name: PakAzureComPool 

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**\*.dacpac'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true